[build]
  command = "npm install next-themes ethers && npm run netlify-static"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL = "https://sepolia.base.org"
  NEXT_PUBLIC_CHAIN_ID = "84532"
  NEXT_PUBLIC_TSHC_ADDRESS = "0x0859D42FD008D617c087DD386667da51570B1aAB"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_ESLINT = "true"
  TYPESCRIPT_SKIP_CHECKING = "true"
  NEXT_TYPESCRIPT_COMPILE_OPTIONS = "{\"transpileOnly\": true, \"ignoreBuildErrors\": true}"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=8192"
  NEXT_DISABLE_SOURCEMAPS = "true"
  NEXT_DISABLE_ESLINT = "true"
  NEXT_IGNORE_TYPESCRIPT_ERRORS = "true"
  NEXT_IGNORE_ESLINT_ERRORS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["**/*"]
  external_node_modules = ["@swc/*", "@next/swc-*", "@esbuild/linux-x64", "@esbuild/darwin-x64", "@esbuild/darwin-arm64"]

# Remove the redirect to index.html as it conflicts with Next.js routing
