[build]
  command = "bash ./netlify-build-fix.sh"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NEXT_TYPESCRIPT_CHECK = "false"
  NEXT_ESLINT_CHECK = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
