# Production settings for Next.js with static export
[build]
  command = "npm run build && npm run export"
  publish = "out"


# Environment variables
[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Static export mode doesn't need the Next.js plugin
