[build]
  command = "bash ./netlify-static-build.sh"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"

# Handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
