# Production settings for Next.js with static export
[build]
  command = "npm run build"
  publish = ".next"

# Prisma postinstall hook
[build.lifecycle]
  onBuild = "npx prisma generate"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Environment variables
[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = ["node_modules/.prisma/client/**"]
  node_bundler = "esbuild"

# Static export mode doesn't need the Next.js plugin

[cache]
  # Ignore Prisma's generated client and engine to force regeneration
  ignore = [
    "node_modules/.prisma",
    "node_modules/@prisma/client"
  ]
