# Production settings for Next.js with static export
[build]
  command = "NODE_ENV=production npm run build"
  publish = "out"

# Environment variables
[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Force opt-in to all the required features for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Disable Next.js in-source telemetry collection
    skipTelemetry = true
    # Enable all required features for stable SSR + ESM
    frameworkVersion = "experimental"
    # Use standard Next.js builds
    useStandard = true
