[build]
  command = "npm install && npm run build"
  publish = ".next"
  
[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NEXT_TYPESCRIPT_CHECK = "false"
  NEXT_ESLINT_CHECK = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"
