# Production settings for Next.js with static export
[build]
  command = "NODE_ENV=production npm run build"
  publish = "out"

# Environment variables
[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Use the Next.js plugin with default configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
